name: dating_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  antdesign_icons: ^0.0.3
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.9.1
  equatable: ^2.0.5
  eva_icons_flutter: ^3.1.0
  extended_image: ^8.1.1
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  flutter_bloc: ^8.1.3
  flutter_datetime_picker: ^1.5.1
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  transparent_image: ^2.0.1
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  geolocator: ^10.0.1
  google_fonts: ^6.0.0
  image_picker: ^1.0.4
  latlng: ^1.0.0
  lottie: ^2.6.0
  meta: ^1.9.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  step_progress_indicator: ^1.0.2
  story_view: ^0.15.0
  timeago: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/svgs/
